name = "futureAmmo"
mainprefix = "z"
prefix = "futureAmmo"

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
]

exclude = ["*.psd", "*.png", "*.tga"]

[version]
path = "addons/main/script_version.hpp"

[properties]
author = "Ghosts of Battle"
